[versions]
agp = "8.9.2"
kotlin = "2.0.21"

junit = "4.13.2"

installReferrer = "2.2"

[libraries]

# Install Referrer — the SDK's only runtime dependency.
installreferrer = { group = "com.android.installreferrer", name = "installreferrer", version.ref = "installReferrer" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
